/* File: gwswex_f2pywrapper_parallelmodule.c
 * This file is auto-generated with f2py (version:1.23.4).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Sat Mar 16 19:46:31 2024
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *gwswex_f2pywrapper_parallel_error;
static PyObject *gwswex_f2pywrapper_parallel_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(len+1)) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

/*
STRINGPADN replaces null values with padding values from the right.

`to` must have size of at least N bytes.

If the `to[N-1]` has null value, then replace it and all the
preceding, nulls with the given padding.

STRINGPADN(to, N, PADDING, NULLVALUE) is an inverse operation.
*/
#define STRINGPADN(to, N, NULLVALUE, PADDING)                   \
    do {                                                        \
        int _m = (N);                                           \
        char *_to = (to);                                       \
        for (_m -= 1; _m >= 0 && _to[_m] == NULLVALUE; _m--) {  \
             _to[_m] = PADDING;                                 \
        }                                                       \
    } while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

/*
STRINGCOPYN copies N bytes.

`to` and `from` buffers must have sizes of at least N bytes.
*/
#define STRINGCOPYN(to,from,N)                                  \
    do {                                                        \
        int _m = (N);                                           \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, _m);             \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

/*
  Create a new string buffer `str` of at most length `len` from a
  Python string-like object `obj`.

  The string buffer has given size (len) or the size of inistr when len==-1.

  The string buffer is padded with blanks: in Fortran, trailing blanks
  are insignificant contrary to C nulls.
 */
static int
string_from_pyobj(string *str, int *len, const string inistr, PyObject *obj,
                  const char *errmess)
{
    PyObject *tmp = NULL;
    string buf = NULL;
    npy_intp n = -1;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",
               (char*)str, *len, (char *)inistr, obj);
#endif
    if (obj == Py_None) {
        n = strlen(inistr);
        buf = inistr;
    }
    else if (PyArray_Check(obj)) {
        PyArrayObject *arr = (PyArrayObject *)obj;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,
                            "array object is non-contiguous.");
            goto capi_fail;
        }
        n = PyArray_NBYTES(arr);
        buf = PyArray_DATA(arr);
        n = strnlen(buf, n);
    }
    else {
        if (PyBytes_Check(obj)) {
            tmp = obj;
            Py_INCREF(tmp);
        }
        else if (PyUnicode_Check(obj)) {
            tmp = PyUnicode_AsASCIIString(obj);
        }
        else {
            PyObject *tmp2;
            tmp2 = PyObject_Str(obj);
            if (tmp2) {
                tmp = PyUnicode_AsASCIIString(tmp2);
                Py_DECREF(tmp2);
            }
            else {
                tmp = NULL;
            }
        }
        if (tmp == NULL) goto capi_fail;
        n = PyBytes_GET_SIZE(tmp);
        buf = PyBytes_AS_STRING(tmp);
    }
    if (*len == -1) {
        /* TODO: change the type of `len` so that we can remove this */
        if (n > NPY_MAX_INT) {
            PyErr_SetString(PyExc_OverflowError,
                            "object too large for a 32-bit int");
            goto capi_fail;
        }
        *len = n;
    }
    else if (*len < n) {
        /* discard the last (len-n) bytes of input buf */
        n = *len;
    }
    if (n < 0 || *len < 0 || buf == NULL) {
        goto capi_fail;
    }
    STRINGMALLOC(*str, *len);  // *str is allocated with size (*len + 1)
    if (n < *len) {
        /*
          Pad fixed-width string with nulls. The caller will replace
          nulls with blanks when the corresponding argument is not
          intent(c).
        */
        memset(*str + n, '\0', *len - n);
    }
    STRINGCOPYN(*str, buf, n);
    Py_XDECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = gwswex_f2pywrapper_parallel_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ init ************************************/
static char doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_init[] = "\
init(config_path,gw_ini,sw_ini)\n\nWrapper for ``init``.\
\n\nParameters\n----------\n"
"config_path : input string(len=-1)\n"
"gw_ini : input rank-1 array('d') with bounds (f2py_gw_ini_d0)\n"
"sw_ini : input rank-1 array('d') with bounds (f2py_sw_ini_d0)";
/* #declfortranroutine# */
static PyObject *f2py_rout_gwswex_f2pywrapper_parallel_gwswex_init(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,double*,double*,int*,int*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    string config_path = NULL;
    int slen(config_path);
    PyObject *config_path_capi = Py_None;
    double *gw_ini = NULL;
    npy_intp gw_ini_Dims[1] = {-1};
    const int gw_ini_Rank = 1;
    PyArrayObject *capi_gw_ini_tmp = NULL;
    int capi_gw_ini_intent = 0;
    PyObject *gw_ini_capi = Py_None;
    double *sw_ini = NULL;
    npy_intp sw_ini_Dims[1] = {-1};
    const int sw_ini_Rank = 1;
    PyArrayObject *capi_sw_ini_tmp = NULL;
    int capi_sw_ini_intent = 0;
    PyObject *sw_ini_capi = Py_None;
    int f2py_gw_ini_d0 = 0;
    int f2py_sw_ini_d0 = 0;
    static char *capi_kwlist[] = {"config_path","gw_ini","sw_ini",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:gwswex_f2pywrapper_parallel.gwswex.init",\
        capi_kwlist,&config_path_capi,&gw_ini_capi,&sw_ini_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable config_path */
    slen(config_path) = -1;
    f2py_success = string_from_pyobj(&config_path,&slen(config_path),"",config_path_capi,"string_from_pyobj failed in converting 1st argument`config_path' of gwswex_f2pywrapper_parallel.gwswex.init to C string");
    if (f2py_success) {
        STRINGPADN(config_path, slen(config_path), '\0', ' ');
    /* Processing variable gw_ini */
    ;
    capi_gw_ini_intent |= F2PY_INTENT_IN;
    capi_gw_ini_tmp = array_from_pyobj(NPY_DOUBLE,gw_ini_Dims,gw_ini_Rank,capi_gw_ini_intent,gw_ini_capi);
    if (capi_gw_ini_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 2nd argument `gw_ini' of gwswex_f2pywrapper_parallel.gwswex.init to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        gw_ini = (double *)(PyArray_DATA(capi_gw_ini_tmp));

    /* Processing variable sw_ini */
    ;
    capi_sw_ini_intent |= F2PY_INTENT_IN;
    capi_sw_ini_tmp = array_from_pyobj(NPY_DOUBLE,sw_ini_Dims,sw_ini_Rank,capi_sw_ini_intent,sw_ini_capi);
    if (capi_sw_ini_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 3rd argument `sw_ini' of gwswex_f2pywrapper_parallel.gwswex.init to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        sw_ini = (double *)(PyArray_DATA(capi_sw_ini_tmp));

    /* Processing variable f2py_gw_ini_d0 */
    f2py_gw_ini_d0 = shape(gw_ini, 0);
    /* Processing variable f2py_sw_ini_d0 */
    f2py_sw_ini_d0 = shape(sw_ini, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(config_path,gw_ini,sw_ini,&f2py_gw_ini_d0,&f2py_sw_ini_d0,slen(config_path));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_sw_ini_d0 */
    /* End of cleaning variable f2py_gw_ini_d0 */
    if((PyObject *)capi_sw_ini_tmp!=sw_ini_capi) {
        Py_XDECREF(capi_sw_ini_tmp); }
    }  /*if (capi_sw_ini_tmp == NULL) ... else of sw_ini*/
    /* End of cleaning variable sw_ini */
    if((PyObject *)capi_gw_ini_tmp!=gw_ini_capi) {
        Py_XDECREF(capi_gw_ini_tmp); }
    }  /*if (capi_gw_ini_tmp == NULL) ... else of gw_ini*/
    /* End of cleaning variable gw_ini */
        STRINGFREE(config_path);
    }  /*if (f2py_success) of config_path*/
    /* End of cleaning variable config_path */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************** end of init ********************************/

/********************************** get_lnts **********************************/
static char doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_get_lnts[] = "\
lnts = get_lnts()\n\nWrapper for ``get_lnts``.\
\n\nReturns\n-------\n"
"lnts : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_gwswex_f2pywrapper_parallel_gwswex_get_lnts(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int get_lnts = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:gwswex_f2pywrapper_parallel.gwswex.get_lnts",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable get_lnts */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&get_lnts);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",get_lnts);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable get_lnts */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of get_lnts ******************************/

/********************************** get_gts **********************************/
static char doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_get_gts[] = "\
gts = get_gts()\n\nWrapper for ``get_gts``.\
\n\nReturns\n-------\n"
"gts : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_gwswex_f2pywrapper_parallel_gwswex_get_gts(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int get_gts = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:gwswex_f2pywrapper_parallel.gwswex.get_gts",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable get_gts */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&get_gts);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",get_gts);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable get_gts */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of get_gts *******************************/

/***************************** get_curr_time_unix *****************************/
static char doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_get_curr_time_unix[] = "\
unix_time = get_curr_time_unix()\n\nWrapper for ``get_curr_time_unix``.\
\n\nReturns\n-------\n"
"unix_time : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_gwswex_f2pywrapper_parallel_gwswex_get_curr_time_unix(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int get_curr_time_unix = 0;
    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:gwswex_f2pywrapper_parallel.gwswex.get_curr_time_unix",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
    /* Processing variable get_curr_time_unix */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&get_curr_time_unix);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("i",get_curr_time_unix);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable get_curr_time_unix */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/************************* end of get_curr_time_unix *************************/

/******************************** grab_result ********************************/
static char doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_grab_result[] = "\
grab_result(code,result)\n\nWrapper for ``grab_result``.\
\n\nParameters\n----------\n"
"code : input string(len=-1)\n"
"result : in/output rank-2 array('d') with bounds (f2py_result_d0,f2py_result_d1)";
/* #declfortranroutine# */
static PyObject *f2py_rout_gwswex_f2pywrapper_parallel_gwswex_grab_result(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,double*,int*,int*,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    string code = NULL;
    int slen(code);
    PyObject *code_capi = Py_None;
    double *result = NULL;
    npy_intp result_Dims[2] = {-1, -1};
    const int result_Rank = 2;
    PyArrayObject *capi_result_tmp = NULL;
    int capi_result_intent = 0;
    PyObject *result_capi = Py_None;
    int f2py_result_d0 = 0;
    int f2py_result_d1 = 0;
    static char *capi_kwlist[] = {"code","result",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:gwswex_f2pywrapper_parallel.gwswex.grab_result",\
        capi_kwlist,&code_capi,&result_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable code */
    slen(code) = -1;
    f2py_success = string_from_pyobj(&code,&slen(code),"",code_capi,"string_from_pyobj failed in converting 1st argument`code' of gwswex_f2pywrapper_parallel.gwswex.grab_result to C string");
    if (f2py_success) {
        STRINGPADN(code, slen(code), '\0', ' ');
    /* Processing variable result */
    ;
    capi_result_intent |= F2PY_INTENT_INOUT;
    capi_result_tmp = array_from_pyobj(NPY_DOUBLE,result_Dims,result_Rank,capi_result_intent,result_capi);
    if (capi_result_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 2nd argument `result' of gwswex_f2pywrapper_parallel.gwswex.grab_result to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        result = (double *)(PyArray_DATA(capi_result_tmp));

    /* Processing variable f2py_result_d0 */
    f2py_result_d0 = shape(result, 0);
    /* Processing variable f2py_result_d1 */
    f2py_result_d1 = shape(result, 1);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(code,result,&f2py_result_d0,&f2py_result_d1,slen(code));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_result_d1 */
    /* End of cleaning variable f2py_result_d0 */
    if((PyObject *)capi_result_tmp!=result_capi) {
        Py_XDECREF(capi_result_tmp); }
    }  /*if (capi_result_tmp == NULL) ... else of result*/
    /* End of cleaning variable result */
        STRINGFREE(code);
    }  /*if (f2py_success) of code*/
    /* End of cleaning variable code */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of grab_result *****************************/

/*********************************** update ***********************************/
static char doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_update[] = "\
update(auto_advance)\n\nWrapper for ``update``.\
\n\nParameters\n----------\n"
"auto_advance : input int";
/*  */
static PyObject *f2py_rout_gwswex_f2pywrapper_parallel_gwswex_update(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(char*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    char auto_advance = 0;
    PyObject *auto_advance_capi = Py_None;
    static char *capi_kwlist[] = {"auto_advance",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|:gwswex_f2pywrapper_parallel.gwswex.update",\
        capi_kwlist,&auto_advance_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable auto_advance */
        auto_advance = (char)PyObject_IsTrue(auto_advance_capi);
        f2py_success = 1;
    if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&auto_advance);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    } /*if (f2py_success) of auto_advance*/
    /* End of cleaning variable auto_advance */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of update *******************************/

/********************************* update_ini *********************************/
static char doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_update_ini[] = "\
update_ini(auto_advance,[gw_ini,sw_ini])\n\nWrapper for ``update_ini``.\
\n\nParameters\n----------\n"
"auto_advance : input int\n"
"\nOther Parameters\n----------------\n"
"gw_ini : input rank-1 array('d') with bounds (f2py_gw_ini_d0)\n"
"sw_ini : input rank-1 array('d') with bounds (f2py_sw_ini_d0)";
/* #declfortranroutine# */
static PyObject *f2py_rout_gwswex_f2pywrapper_parallel_gwswex_update_ini(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(char*,double*,double*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    char auto_advance = 0;
    PyObject *auto_advance_capi = Py_None;
    double *gw_ini = NULL;
    npy_intp gw_ini_Dims[1] = {-1};
    const int gw_ini_Rank = 1;
    PyArrayObject *capi_gw_ini_tmp = NULL;
    int capi_gw_ini_intent = 0;
    PyObject *gw_ini_capi = Py_None;
    double *sw_ini = NULL;
    npy_intp sw_ini_Dims[1] = {-1};
    const int sw_ini_Rank = 1;
    PyArrayObject *capi_sw_ini_tmp = NULL;
    int capi_sw_ini_intent = 0;
    PyObject *sw_ini_capi = Py_None;
    int f2py_gw_ini_d0 = 0;
    int f2py_sw_ini_d0 = 0;
    static char *capi_kwlist[] = {"auto_advance","gw_ini","sw_ini",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "O|OO:gwswex_f2pywrapper_parallel.gwswex.update_ini",\
        capi_kwlist,&auto_advance_capi,&gw_ini_capi,&sw_ini_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable auto_advance */
        auto_advance = (char)PyObject_IsTrue(auto_advance_capi);
        f2py_success = 1;
    if (f2py_success) {
    /* Processing variable gw_ini */
    ;
    capi_gw_ini_intent |= F2PY_INTENT_IN|F2PY_OPTIONAL;
    capi_gw_ini_tmp = array_from_pyobj(NPY_DOUBLE,gw_ini_Dims,gw_ini_Rank,capi_gw_ini_intent,gw_ini_capi);
    if (capi_gw_ini_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 1st keyword `gw_ini' of gwswex_f2pywrapper_parallel.gwswex.update_ini to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        gw_ini = (double *)(PyArray_DATA(capi_gw_ini_tmp));

    /* Processing variable sw_ini */
    ;
    capi_sw_ini_intent |= F2PY_INTENT_IN|F2PY_OPTIONAL;
    capi_sw_ini_tmp = array_from_pyobj(NPY_DOUBLE,sw_ini_Dims,sw_ini_Rank,capi_sw_ini_intent,sw_ini_capi);
    if (capi_sw_ini_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 2nd keyword `sw_ini' of gwswex_f2pywrapper_parallel.gwswex.update_ini to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        sw_ini = (double *)(PyArray_DATA(capi_sw_ini_tmp));

    /* Processing variable f2py_gw_ini_d0 */
    f2py_gw_ini_d0 = shape(gw_ini, 0);
    /* Processing variable f2py_sw_ini_d0 */
    f2py_sw_ini_d0 = shape(sw_ini, 0);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(&auto_advance,gw_ini,sw_ini,&f2py_gw_ini_d0,&f2py_sw_ini_d0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_sw_ini_d0 */
    /* End of cleaning variable f2py_gw_ini_d0 */
    if((PyObject *)capi_sw_ini_tmp!=sw_ini_capi) {
        Py_XDECREF(capi_sw_ini_tmp); }
    }  /*if (capi_sw_ini_tmp == NULL) ... else of sw_ini*/
    /* End of cleaning variable sw_ini */
    if((PyObject *)capi_gw_ini_tmp!=gw_ini_capi) {
        Py_XDECREF(capi_gw_ini_tmp); }
    }  /*if (capi_gw_ini_tmp == NULL) ... else of gw_ini*/
    /* End of cleaning variable gw_ini */
    } /*if (f2py_success) of auto_advance*/
    /* End of cleaning variable auto_advance */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of update_ini *****************************/

/************************************ run ************************************/
static char doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_run[] = "\
run()\n\nWrapper for ``run``.\
\n";
/*  */
static PyObject *f2py_rout_gwswex_f2pywrapper_parallel_gwswex_run(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:gwswex_f2pywrapper_parallel.gwswex.run",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/********************************* end of run *********************************/

/********************************** resolve **********************************/
static char doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_resolve[] = "\
resolve(gws_ext,sws_ext)\n\nWrapper for ``resolve``.\
\n\nParameters\n----------\n"
"gws_ext : input rank-2 array('d') with bounds (f2py_gws_ext_d0,f2py_gws_ext_d1)\n"
"sws_ext : input rank-2 array('d') with bounds (f2py_sws_ext_d0,f2py_sws_ext_d1)";
/* #declfortranroutine# */
static PyObject *f2py_rout_gwswex_f2pywrapper_parallel_gwswex_resolve(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *gws_ext = NULL;
    npy_intp gws_ext_Dims[2] = {-1, -1};
    const int gws_ext_Rank = 2;
    PyArrayObject *capi_gws_ext_tmp = NULL;
    int capi_gws_ext_intent = 0;
    PyObject *gws_ext_capi = Py_None;
    double *sws_ext = NULL;
    npy_intp sws_ext_Dims[2] = {-1, -1};
    const int sws_ext_Rank = 2;
    PyArrayObject *capi_sws_ext_tmp = NULL;
    int capi_sws_ext_intent = 0;
    PyObject *sws_ext_capi = Py_None;
    int f2py_gws_ext_d0 = 0;
    int f2py_gws_ext_d1 = 0;
    int f2py_sws_ext_d0 = 0;
    int f2py_sws_ext_d1 = 0;
    static char *capi_kwlist[] = {"gws_ext","sws_ext",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OO|:gwswex_f2pywrapper_parallel.gwswex.resolve",\
        capi_kwlist,&gws_ext_capi,&sws_ext_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable gws_ext */
    ;
    capi_gws_ext_intent |= F2PY_INTENT_IN;
    capi_gws_ext_tmp = array_from_pyobj(NPY_DOUBLE,gws_ext_Dims,gws_ext_Rank,capi_gws_ext_intent,gws_ext_capi);
    if (capi_gws_ext_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 1st argument `gws_ext' of gwswex_f2pywrapper_parallel.gwswex.resolve to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        gws_ext = (double *)(PyArray_DATA(capi_gws_ext_tmp));

    /* Processing variable sws_ext */
    ;
    capi_sws_ext_intent |= F2PY_INTENT_IN;
    capi_sws_ext_tmp = array_from_pyobj(NPY_DOUBLE,sws_ext_Dims,sws_ext_Rank,capi_sws_ext_intent,sws_ext_capi);
    if (capi_sws_ext_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 2nd argument `sws_ext' of gwswex_f2pywrapper_parallel.gwswex.resolve to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        sws_ext = (double *)(PyArray_DATA(capi_sws_ext_tmp));

    /* Processing variable f2py_gws_ext_d0 */
    f2py_gws_ext_d0 = shape(gws_ext, 0);
    /* Processing variable f2py_gws_ext_d1 */
    f2py_gws_ext_d1 = shape(gws_ext, 1);
    /* Processing variable f2py_sws_ext_d0 */
    f2py_sws_ext_d0 = shape(sws_ext, 0);
    /* Processing variable f2py_sws_ext_d1 */
    f2py_sws_ext_d1 = shape(sws_ext, 1);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(gws_ext,sws_ext,&f2py_gws_ext_d0,&f2py_gws_ext_d1,&f2py_sws_ext_d0,&f2py_sws_ext_d1);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_sws_ext_d1 */
    /* End of cleaning variable f2py_sws_ext_d0 */
    /* End of cleaning variable f2py_gws_ext_d1 */
    /* End of cleaning variable f2py_gws_ext_d0 */
    if((PyObject *)capi_sws_ext_tmp!=sws_ext_capi) {
        Py_XDECREF(capi_sws_ext_tmp); }
    }  /*if (capi_sws_ext_tmp == NULL) ... else of sws_ext*/
    /* End of cleaning variable sws_ext */
    if((PyObject *)capi_gws_ext_tmp!=gws_ext_capi) {
        Py_XDECREF(capi_gws_ext_tmp); }
    }  /*if (capi_gws_ext_tmp == NULL) ... else of gws_ext*/
    /* End of cleaning variable gws_ext */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/******************************* end of resolve *******************************/

/********************************* pass_vars *********************************/
static char doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_pass_vars[] = "\
pass_vars(gws,sws,sms,epv)\n\nWrapper for ``pass_vars``.\
\n\nParameters\n----------\n"
"gws : in/output rank-2 array('d') with bounds (f2py_gws_d0,f2py_gws_d1)\n"
"sws : in/output rank-2 array('d') with bounds (f2py_sws_d0,f2py_sws_d1)\n"
"sms : in/output rank-2 array('d') with bounds (f2py_sms_d0,f2py_sms_d1)\n"
"epv : in/output rank-2 array('d') with bounds (f2py_epv_d0,f2py_epv_d1)";
/* #declfortranroutine# */
static PyObject *f2py_rout_gwswex_f2pywrapper_parallel_gwswex_pass_vars(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *gws = NULL;
    npy_intp gws_Dims[2] = {-1, -1};
    const int gws_Rank = 2;
    PyArrayObject *capi_gws_tmp = NULL;
    int capi_gws_intent = 0;
    PyObject *gws_capi = Py_None;
    double *sws = NULL;
    npy_intp sws_Dims[2] = {-1, -1};
    const int sws_Rank = 2;
    PyArrayObject *capi_sws_tmp = NULL;
    int capi_sws_intent = 0;
    PyObject *sws_capi = Py_None;
    double *sms = NULL;
    npy_intp sms_Dims[2] = {-1, -1};
    const int sms_Rank = 2;
    PyArrayObject *capi_sms_tmp = NULL;
    int capi_sms_intent = 0;
    PyObject *sms_capi = Py_None;
    double *epv = NULL;
    npy_intp epv_Dims[2] = {-1, -1};
    const int epv_Rank = 2;
    PyArrayObject *capi_epv_tmp = NULL;
    int capi_epv_intent = 0;
    PyObject *epv_capi = Py_None;
    int f2py_gws_d0 = 0;
    int f2py_gws_d1 = 0;
    int f2py_sws_d0 = 0;
    int f2py_sws_d1 = 0;
    int f2py_sms_d0 = 0;
    int f2py_sms_d1 = 0;
    int f2py_epv_d0 = 0;
    int f2py_epv_d1 = 0;
    static char *capi_kwlist[] = {"gws","sws","sms","epv",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|:gwswex_f2pywrapper_parallel.gwswex.pass_vars",\
        capi_kwlist,&gws_capi,&sws_capi,&sms_capi,&epv_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable gws */
    ;
    capi_gws_intent |= F2PY_INTENT_INOUT;
    capi_gws_tmp = array_from_pyobj(NPY_DOUBLE,gws_Dims,gws_Rank,capi_gws_intent,gws_capi);
    if (capi_gws_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 1st argument `gws' of gwswex_f2pywrapper_parallel.gwswex.pass_vars to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        gws = (double *)(PyArray_DATA(capi_gws_tmp));

    /* Processing variable sws */
    ;
    capi_sws_intent |= F2PY_INTENT_INOUT;
    capi_sws_tmp = array_from_pyobj(NPY_DOUBLE,sws_Dims,sws_Rank,capi_sws_intent,sws_capi);
    if (capi_sws_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 2nd argument `sws' of gwswex_f2pywrapper_parallel.gwswex.pass_vars to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        sws = (double *)(PyArray_DATA(capi_sws_tmp));

    /* Processing variable sms */
    ;
    capi_sms_intent |= F2PY_INTENT_INOUT;
    capi_sms_tmp = array_from_pyobj(NPY_DOUBLE,sms_Dims,sms_Rank,capi_sms_intent,sms_capi);
    if (capi_sms_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 3rd argument `sms' of gwswex_f2pywrapper_parallel.gwswex.pass_vars to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        sms = (double *)(PyArray_DATA(capi_sms_tmp));

    /* Processing variable epv */
    ;
    capi_epv_intent |= F2PY_INTENT_INOUT;
    capi_epv_tmp = array_from_pyobj(NPY_DOUBLE,epv_Dims,epv_Rank,capi_epv_intent,epv_capi);
    if (capi_epv_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 4th argument `epv' of gwswex_f2pywrapper_parallel.gwswex.pass_vars to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        epv = (double *)(PyArray_DATA(capi_epv_tmp));

    /* Processing variable f2py_gws_d0 */
    f2py_gws_d0 = shape(gws, 0);
    /* Processing variable f2py_gws_d1 */
    f2py_gws_d1 = shape(gws, 1);
    /* Processing variable f2py_sws_d0 */
    f2py_sws_d0 = shape(sws, 0);
    /* Processing variable f2py_sws_d1 */
    f2py_sws_d1 = shape(sws, 1);
    /* Processing variable f2py_sms_d0 */
    f2py_sms_d0 = shape(sms, 0);
    /* Processing variable f2py_sms_d1 */
    f2py_sms_d1 = shape(sms, 1);
    /* Processing variable f2py_epv_d0 */
    f2py_epv_d0 = shape(epv, 0);
    /* Processing variable f2py_epv_d1 */
    f2py_epv_d1 = shape(epv, 1);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(gws,sws,sms,epv,&f2py_gws_d0,&f2py_gws_d1,&f2py_sws_d0,&f2py_sws_d1,&f2py_sms_d0,&f2py_sms_d1,&f2py_epv_d0,&f2py_epv_d1);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_epv_d1 */
    /* End of cleaning variable f2py_epv_d0 */
    /* End of cleaning variable f2py_sms_d1 */
    /* End of cleaning variable f2py_sms_d0 */
    /* End of cleaning variable f2py_sws_d1 */
    /* End of cleaning variable f2py_sws_d0 */
    /* End of cleaning variable f2py_gws_d1 */
    /* End of cleaning variable f2py_gws_d0 */
    if((PyObject *)capi_epv_tmp!=epv_capi) {
        Py_XDECREF(capi_epv_tmp); }
    }  /*if (capi_epv_tmp == NULL) ... else of epv*/
    /* End of cleaning variable epv */
    if((PyObject *)capi_sms_tmp!=sms_capi) {
        Py_XDECREF(capi_sms_tmp); }
    }  /*if (capi_sms_tmp == NULL) ... else of sms*/
    /* End of cleaning variable sms */
    if((PyObject *)capi_sws_tmp!=sws_capi) {
        Py_XDECREF(capi_sws_tmp); }
    }  /*if (capi_sws_tmp == NULL) ... else of sws*/
    /* End of cleaning variable sws */
    if((PyObject *)capi_gws_tmp!=gws_capi) {
        Py_XDECREF(capi_gws_tmp); }
    }  /*if (capi_gws_tmp == NULL) ... else of gws*/
    /* End of cleaning variable gws */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of pass_vars ******************************/

/******************************* pass_vars_nlay *******************************/
static char doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_pass_vars_nlay[] = "\
pass_vars_nlay(gws,sws,sms,epv)\n\nWrapper for ``pass_vars_nlay``.\
\n\nParameters\n----------\n"
"gws : in/output rank-2 array('d') with bounds (f2py_gws_d0,f2py_gws_d1)\n"
"sws : in/output rank-2 array('d') with bounds (f2py_sws_d0,f2py_sws_d1)\n"
"sms : in/output rank-3 array('d') with bounds (f2py_sms_d0,f2py_sms_d1,f2py_sms_d2)\n"
"epv : in/output rank-3 array('d') with bounds (f2py_epv_d0,f2py_epv_d1,f2py_epv_d2)";
/* #declfortranroutine# */
static PyObject *f2py_rout_gwswex_f2pywrapper_parallel_gwswex_pass_vars_nlay(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *gws = NULL;
    npy_intp gws_Dims[2] = {-1, -1};
    const int gws_Rank = 2;
    PyArrayObject *capi_gws_tmp = NULL;
    int capi_gws_intent = 0;
    PyObject *gws_capi = Py_None;
    double *sws = NULL;
    npy_intp sws_Dims[2] = {-1, -1};
    const int sws_Rank = 2;
    PyArrayObject *capi_sws_tmp = NULL;
    int capi_sws_intent = 0;
    PyObject *sws_capi = Py_None;
    double *sms = NULL;
    npy_intp sms_Dims[3] = {-1, -1, -1};
    const int sms_Rank = 3;
    PyArrayObject *capi_sms_tmp = NULL;
    int capi_sms_intent = 0;
    PyObject *sms_capi = Py_None;
    double *epv = NULL;
    npy_intp epv_Dims[3] = {-1, -1, -1};
    const int epv_Rank = 3;
    PyArrayObject *capi_epv_tmp = NULL;
    int capi_epv_intent = 0;
    PyObject *epv_capi = Py_None;
    int f2py_gws_d0 = 0;
    int f2py_gws_d1 = 0;
    int f2py_sws_d0 = 0;
    int f2py_sws_d1 = 0;
    int f2py_sms_d0 = 0;
    int f2py_sms_d1 = 0;
    int f2py_sms_d2 = 0;
    int f2py_epv_d0 = 0;
    int f2py_epv_d1 = 0;
    int f2py_epv_d2 = 0;
    static char *capi_kwlist[] = {"gws","sws","sms","epv",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|:gwswex_f2pywrapper_parallel.gwswex.pass_vars_nlay",\
        capi_kwlist,&gws_capi,&sws_capi,&sms_capi,&epv_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable gws */
    ;
    capi_gws_intent |= F2PY_INTENT_INOUT;
    capi_gws_tmp = array_from_pyobj(NPY_DOUBLE,gws_Dims,gws_Rank,capi_gws_intent,gws_capi);
    if (capi_gws_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 1st argument `gws' of gwswex_f2pywrapper_parallel.gwswex.pass_vars_nlay to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        gws = (double *)(PyArray_DATA(capi_gws_tmp));

    /* Processing variable sws */
    ;
    capi_sws_intent |= F2PY_INTENT_INOUT;
    capi_sws_tmp = array_from_pyobj(NPY_DOUBLE,sws_Dims,sws_Rank,capi_sws_intent,sws_capi);
    if (capi_sws_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 2nd argument `sws' of gwswex_f2pywrapper_parallel.gwswex.pass_vars_nlay to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        sws = (double *)(PyArray_DATA(capi_sws_tmp));

    /* Processing variable sms */
    ;
    capi_sms_intent |= F2PY_INTENT_INOUT;
    capi_sms_tmp = array_from_pyobj(NPY_DOUBLE,sms_Dims,sms_Rank,capi_sms_intent,sms_capi);
    if (capi_sms_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 3rd argument `sms' of gwswex_f2pywrapper_parallel.gwswex.pass_vars_nlay to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        sms = (double *)(PyArray_DATA(capi_sms_tmp));

    /* Processing variable epv */
    ;
    capi_epv_intent |= F2PY_INTENT_INOUT;
    capi_epv_tmp = array_from_pyobj(NPY_DOUBLE,epv_Dims,epv_Rank,capi_epv_intent,epv_capi);
    if (capi_epv_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 4th argument `epv' of gwswex_f2pywrapper_parallel.gwswex.pass_vars_nlay to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        epv = (double *)(PyArray_DATA(capi_epv_tmp));

    /* Processing variable f2py_gws_d0 */
    f2py_gws_d0 = shape(gws, 0);
    /* Processing variable f2py_gws_d1 */
    f2py_gws_d1 = shape(gws, 1);
    /* Processing variable f2py_sws_d0 */
    f2py_sws_d0 = shape(sws, 0);
    /* Processing variable f2py_sws_d1 */
    f2py_sws_d1 = shape(sws, 1);
    /* Processing variable f2py_sms_d0 */
    f2py_sms_d0 = shape(sms, 0);
    /* Processing variable f2py_sms_d1 */
    f2py_sms_d1 = shape(sms, 1);
    /* Processing variable f2py_sms_d2 */
    f2py_sms_d2 = shape(sms, 2);
    /* Processing variable f2py_epv_d0 */
    f2py_epv_d0 = shape(epv, 0);
    /* Processing variable f2py_epv_d1 */
    f2py_epv_d1 = shape(epv, 1);
    /* Processing variable f2py_epv_d2 */
    f2py_epv_d2 = shape(epv, 2);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(gws,sws,sms,epv,&f2py_gws_d0,&f2py_gws_d1,&f2py_sws_d0,&f2py_sws_d1,&f2py_sms_d0,&f2py_sms_d1,&f2py_sms_d2,&f2py_epv_d0,&f2py_epv_d1,&f2py_epv_d2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_epv_d2 */
    /* End of cleaning variable f2py_epv_d1 */
    /* End of cleaning variable f2py_epv_d0 */
    /* End of cleaning variable f2py_sms_d2 */
    /* End of cleaning variable f2py_sms_d1 */
    /* End of cleaning variable f2py_sms_d0 */
    /* End of cleaning variable f2py_sws_d1 */
    /* End of cleaning variable f2py_sws_d0 */
    /* End of cleaning variable f2py_gws_d1 */
    /* End of cleaning variable f2py_gws_d0 */
    if((PyObject *)capi_epv_tmp!=epv_capi) {
        Py_XDECREF(capi_epv_tmp); }
    }  /*if (capi_epv_tmp == NULL) ... else of epv*/
    /* End of cleaning variable epv */
    if((PyObject *)capi_sms_tmp!=sms_capi) {
        Py_XDECREF(capi_sms_tmp); }
    }  /*if (capi_sms_tmp == NULL) ... else of sms*/
    /* End of cleaning variable sms */
    if((PyObject *)capi_sws_tmp!=sws_capi) {
        Py_XDECREF(capi_sws_tmp); }
    }  /*if (capi_sws_tmp == NULL) ... else of sws*/
    /* End of cleaning variable sws */
    if((PyObject *)capi_gws_tmp!=gws_capi) {
        Py_XDECREF(capi_gws_tmp); }
    }  /*if (capi_gws_tmp == NULL) ... else of gws*/
    /* End of cleaning variable gws */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*************************** end of pass_vars_nlay ***************************/

/********************************** pass_dis **********************************/
static char doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_pass_dis[] = "\
pass_dis(gw_dis,uz_dis,sw_dis,qdiff_l)\n\nWrapper for ``pass_dis``.\
\n\nParameters\n----------\n"
"gw_dis : in/output rank-2 array('d') with bounds (f2py_gw_dis_d0,f2py_gw_dis_d1)\n"
"uz_dis : in/output rank-2 array('d') with bounds (f2py_uz_dis_d0,f2py_uz_dis_d1)\n"
"sw_dis : in/output rank-2 array('d') with bounds (f2py_sw_dis_d0,f2py_sw_dis_d1)\n"
"qdiff_l : in/output rank-2 array('d') with bounds (f2py_qdiff_l_d0,f2py_qdiff_l_d1)";
/* #declfortranroutine# */
static PyObject *f2py_rout_gwswex_f2pywrapper_parallel_gwswex_pass_dis(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    double *gw_dis = NULL;
    npy_intp gw_dis_Dims[2] = {-1, -1};
    const int gw_dis_Rank = 2;
    PyArrayObject *capi_gw_dis_tmp = NULL;
    int capi_gw_dis_intent = 0;
    PyObject *gw_dis_capi = Py_None;
    double *uz_dis = NULL;
    npy_intp uz_dis_Dims[2] = {-1, -1};
    const int uz_dis_Rank = 2;
    PyArrayObject *capi_uz_dis_tmp = NULL;
    int capi_uz_dis_intent = 0;
    PyObject *uz_dis_capi = Py_None;
    double *sw_dis = NULL;
    npy_intp sw_dis_Dims[2] = {-1, -1};
    const int sw_dis_Rank = 2;
    PyArrayObject *capi_sw_dis_tmp = NULL;
    int capi_sw_dis_intent = 0;
    PyObject *sw_dis_capi = Py_None;
    double *qdiff_l = NULL;
    npy_intp qdiff_l_Dims[2] = {-1, -1};
    const int qdiff_l_Rank = 2;
    PyArrayObject *capi_qdiff_l_tmp = NULL;
    int capi_qdiff_l_intent = 0;
    PyObject *qdiff_l_capi = Py_None;
    int f2py_gw_dis_d0 = 0;
    int f2py_gw_dis_d1 = 0;
    int f2py_uz_dis_d0 = 0;
    int f2py_uz_dis_d1 = 0;
    int f2py_sw_dis_d0 = 0;
    int f2py_sw_dis_d1 = 0;
    int f2py_qdiff_l_d0 = 0;
    int f2py_qdiff_l_d1 = 0;
    static char *capi_kwlist[] = {"gw_dis","uz_dis","sw_dis","qdiff_l",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOO|:gwswex_f2pywrapper_parallel.gwswex.pass_dis",\
        capi_kwlist,&gw_dis_capi,&uz_dis_capi,&sw_dis_capi,&qdiff_l_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable gw_dis */
    ;
    capi_gw_dis_intent |= F2PY_INTENT_INOUT;
    capi_gw_dis_tmp = array_from_pyobj(NPY_DOUBLE,gw_dis_Dims,gw_dis_Rank,capi_gw_dis_intent,gw_dis_capi);
    if (capi_gw_dis_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 1st argument `gw_dis' of gwswex_f2pywrapper_parallel.gwswex.pass_dis to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        gw_dis = (double *)(PyArray_DATA(capi_gw_dis_tmp));

    /* Processing variable uz_dis */
    ;
    capi_uz_dis_intent |= F2PY_INTENT_INOUT;
    capi_uz_dis_tmp = array_from_pyobj(NPY_DOUBLE,uz_dis_Dims,uz_dis_Rank,capi_uz_dis_intent,uz_dis_capi);
    if (capi_uz_dis_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 2nd argument `uz_dis' of gwswex_f2pywrapper_parallel.gwswex.pass_dis to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        uz_dis = (double *)(PyArray_DATA(capi_uz_dis_tmp));

    /* Processing variable sw_dis */
    ;
    capi_sw_dis_intent |= F2PY_INTENT_INOUT;
    capi_sw_dis_tmp = array_from_pyobj(NPY_DOUBLE,sw_dis_Dims,sw_dis_Rank,capi_sw_dis_intent,sw_dis_capi);
    if (capi_sw_dis_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 3rd argument `sw_dis' of gwswex_f2pywrapper_parallel.gwswex.pass_dis to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        sw_dis = (double *)(PyArray_DATA(capi_sw_dis_tmp));

    /* Processing variable qdiff_l */
    ;
    capi_qdiff_l_intent |= F2PY_INTENT_INOUT;
    capi_qdiff_l_tmp = array_from_pyobj(NPY_DOUBLE,qdiff_l_Dims,qdiff_l_Rank,capi_qdiff_l_intent,qdiff_l_capi);
    if (capi_qdiff_l_tmp == NULL) {
        PyObject *exc, *val, *tb;
        PyErr_Fetch(&exc, &val, &tb);
        PyErr_SetString(exc ? exc : gwswex_f2pywrapper_parallel_error,"failed in converting 4th argument `qdiff_l' of gwswex_f2pywrapper_parallel.gwswex.pass_dis to C/Fortran array" );
        npy_PyErr_ChainExceptionsCause(exc, val, tb);
    } else {
        qdiff_l = (double *)(PyArray_DATA(capi_qdiff_l_tmp));

    /* Processing variable f2py_gw_dis_d0 */
    f2py_gw_dis_d0 = shape(gw_dis, 0);
    /* Processing variable f2py_gw_dis_d1 */
    f2py_gw_dis_d1 = shape(gw_dis, 1);
    /* Processing variable f2py_uz_dis_d0 */
    f2py_uz_dis_d0 = shape(uz_dis, 0);
    /* Processing variable f2py_uz_dis_d1 */
    f2py_uz_dis_d1 = shape(uz_dis, 1);
    /* Processing variable f2py_sw_dis_d0 */
    f2py_sw_dis_d0 = shape(sw_dis, 0);
    /* Processing variable f2py_sw_dis_d1 */
    f2py_sw_dis_d1 = shape(sw_dis, 1);
    /* Processing variable f2py_qdiff_l_d0 */
    f2py_qdiff_l_d0 = shape(qdiff_l, 0);
    /* Processing variable f2py_qdiff_l_d1 */
    f2py_qdiff_l_d1 = shape(qdiff_l, 1);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    (*f2py_func)(gw_dis,uz_dis,sw_dis,qdiff_l,&f2py_gw_dis_d0,&f2py_gw_dis_d1,&f2py_uz_dis_d0,&f2py_uz_dis_d1,&f2py_sw_dis_d0,&f2py_sw_dis_d1,&f2py_qdiff_l_d0,&f2py_qdiff_l_d1);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    /* End of cleaning variable f2py_qdiff_l_d1 */
    /* End of cleaning variable f2py_qdiff_l_d0 */
    /* End of cleaning variable f2py_sw_dis_d1 */
    /* End of cleaning variable f2py_sw_dis_d0 */
    /* End of cleaning variable f2py_uz_dis_d1 */
    /* End of cleaning variable f2py_uz_dis_d0 */
    /* End of cleaning variable f2py_gw_dis_d1 */
    /* End of cleaning variable f2py_gw_dis_d0 */
    if((PyObject *)capi_qdiff_l_tmp!=qdiff_l_capi) {
        Py_XDECREF(capi_qdiff_l_tmp); }
    }  /*if (capi_qdiff_l_tmp == NULL) ... else of qdiff_l*/
    /* End of cleaning variable qdiff_l */
    if((PyObject *)capi_sw_dis_tmp!=sw_dis_capi) {
        Py_XDECREF(capi_sw_dis_tmp); }
    }  /*if (capi_sw_dis_tmp == NULL) ... else of sw_dis*/
    /* End of cleaning variable sw_dis */
    if((PyObject *)capi_uz_dis_tmp!=uz_dis_capi) {
        Py_XDECREF(capi_uz_dis_tmp); }
    }  /*if (capi_uz_dis_tmp == NULL) ... else of uz_dis*/
    /* End of cleaning variable uz_dis */
    if((PyObject *)capi_gw_dis_tmp!=gw_dis_capi) {
        Py_XDECREF(capi_gw_dis_tmp); }
    }  /*if (capi_gw_dis_tmp == NULL) ... else of gw_dis*/
    /* End of cleaning variable gw_dis */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of pass_dis ******************************/

/********************************** finalize **********************************/
static char doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_finalize[] = "\
finalize()\n\nWrapper for ``finalize``.\
\n";
/*  */
static PyObject *f2py_rout_gwswex_f2pywrapper_parallel_gwswex_finalize(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(void)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    static char *capi_kwlist[] = {NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "|:gwswex_f2pywrapper_parallel.gwswex.finalize",\
        capi_kwlist))
        return NULL;
/*frompyobj*/
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)();
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of finalize ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_gwswex_def[] = {
  {"strlen",0,{{-1}},NPY_INT},
  {"init",-1,{{-1}},0,NULL,(void *)f2py_rout_gwswex_f2pywrapper_parallel_gwswex_init,doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_init},
  {"get_lnts",-1,{{-1}},0,NULL,(void *)f2py_rout_gwswex_f2pywrapper_parallel_gwswex_get_lnts,doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_get_lnts},
  {"get_gts",-1,{{-1}},0,NULL,(void *)f2py_rout_gwswex_f2pywrapper_parallel_gwswex_get_gts,doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_get_gts},
  {"get_curr_time_unix",-1,{{-1}},0,NULL,(void *)f2py_rout_gwswex_f2pywrapper_parallel_gwswex_get_curr_time_unix,doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_get_curr_time_unix},
  {"grab_result",-1,{{-1}},0,NULL,(void *)f2py_rout_gwswex_f2pywrapper_parallel_gwswex_grab_result,doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_grab_result},
  {"update",-1,{{-1}},0,NULL,(void *)f2py_rout_gwswex_f2pywrapper_parallel_gwswex_update,doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_update},
  {"update_ini",-1,{{-1}},0,NULL,(void *)f2py_rout_gwswex_f2pywrapper_parallel_gwswex_update_ini,doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_update_ini},
  {"run",-1,{{-1}},0,NULL,(void *)f2py_rout_gwswex_f2pywrapper_parallel_gwswex_run,doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_run},
  {"resolve",-1,{{-1}},0,NULL,(void *)f2py_rout_gwswex_f2pywrapper_parallel_gwswex_resolve,doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_resolve},
  {"pass_vars",-1,{{-1}},0,NULL,(void *)f2py_rout_gwswex_f2pywrapper_parallel_gwswex_pass_vars,doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_pass_vars},
  {"pass_vars_nlay",-1,{{-1}},0,NULL,(void *)f2py_rout_gwswex_f2pywrapper_parallel_gwswex_pass_vars_nlay,doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_pass_vars_nlay},
  {"pass_dis",-1,{{-1}},0,NULL,(void *)f2py_rout_gwswex_f2pywrapper_parallel_gwswex_pass_dis,doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_pass_dis},
  {"finalize",-1,{{-1}},0,NULL,(void *)f2py_rout_gwswex_f2pywrapper_parallel_gwswex_finalize,doc_f2py_rout_gwswex_f2pywrapper_parallel_gwswex_finalize},
  {NULL}
};

static void f2py_setup_gwswex(char *strlen,char *init,char *get_lnts,char *get_gts,char *get_curr_time_unix,char *grab_result,char *update,char *update_ini,char *run,char *resolve,char *pass_vars,char *pass_vars_nlay,char *pass_dis,char *finalize) {
  int i_f2py=0;
  f2py_gwswex_def[i_f2py++].data = strlen;
  f2py_gwswex_def[i_f2py++].data = init;
  f2py_gwswex_def[i_f2py++].data = get_lnts;
  f2py_gwswex_def[i_f2py++].data = get_gts;
  f2py_gwswex_def[i_f2py++].data = get_curr_time_unix;
  f2py_gwswex_def[i_f2py++].data = grab_result;
  f2py_gwswex_def[i_f2py++].data = update;
  f2py_gwswex_def[i_f2py++].data = update_ini;
  f2py_gwswex_def[i_f2py++].data = run;
  f2py_gwswex_def[i_f2py++].data = resolve;
  f2py_gwswex_def[i_f2py++].data = pass_vars;
  f2py_gwswex_def[i_f2py++].data = pass_vars_nlay;
  f2py_gwswex_def[i_f2py++].data = pass_dis;
  f2py_gwswex_def[i_f2py++].data = finalize;
}
extern void F_FUNC(f2pyinitgwswex,F2PYINITGWSWEX)(void (*)(char*,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *,char *));
static void f2py_init_gwswex(void) {
  F_FUNC(f2pyinitgwswex,F2PYINITGWSWEX)(f2py_setup_gwswex);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "gwswex_f2pywrapper_parallel",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_gwswex_f2pywrapper_parallel(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = gwswex_f2pywrapper_parallel_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module gwswex_f2pywrapper_parallel (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.23.4");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'gwswex_f2pywrapper_parallel' is auto-generated with f2py (version:1.23.4).\nFunctions:\n"
"Fortran 90/95 modules:\n""  gwswex --- strlen,init(),get_lnts(),get_gts(),get_curr_time_unix(),grab_result(),update(),update_ini(),run(),resolve(),pass_vars(),pass_vars_nlay(),pass_dis(),finalize()"".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.23.4");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    gwswex_f2pywrapper_parallel_error = PyErr_NewException ("gwswex_f2pywrapper_parallel.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_gwswex_f2pywrapper_parallel_error", gwswex_f2pywrapper_parallel_error);
    Py_DECREF(gwswex_f2pywrapper_parallel_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }













/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "gwswex", PyFortranObject_New(f2py_gwswex_def,f2py_init_gwswex));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"gwswex_f2pywrapper_parallel");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
