!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.23.4)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2pywrap_gwswex_init (config_path, gw_ini, sw_ini, f2py&
     &_gw_ini_d0, f2py_sw_ini_d0)
      use gwswex, only : init
      integer f2py_gw_ini_d0
      integer f2py_sw_ini_d0
      character(len=*) config_path
      real(kind=8) gw_ini(f2py_gw_ini_d0)
      real(kind=8) sw_ini(f2py_sw_ini_d0)
      call init(config_path, gw_ini, sw_ini)
      end subroutine f2pywrap_gwswex_init
      subroutine f2pywrap_gwswex_get_lnts (get_lntsf2pywrap)
      use gwswex, only : get_lnts
      integer get_lntsf2pywrap
      get_lntsf2pywrap = get_lnts()
      end subroutine f2pywrap_gwswex_get_lnts
      subroutine f2pywrap_gwswex_get_gts (get_gtsf2pywrap)
      use gwswex, only : get_gts
      integer get_gtsf2pywrap
      get_gtsf2pywrap = get_gts()
      end subroutine f2pywrap_gwswex_get_gts
      subroutine f2pywrap_gwswex_get_curr_time_unix (get_curr_time_unixf&
     &2pywrap)
      use gwswex, only : get_curr_time_unix
      integer get_curr_time_unixf2pywrap
      get_curr_time_unixf2pywrap = get_curr_time_unix()
      end subroutine f2pywrap_gwswex_get_curr_time_unix
      subroutine f2pywrap_gwswex_grab_result (code, result, f2py_result_&
     &d0, f2py_result_d1)
      use gwswex, only : grab_result
                use model, only: gw,sw,uz,uz_
      integer f2py_result_d0
      integer f2py_result_d1
      character(len=*) code
      real(kind=8) result(f2py_result_d0,f2py_result_d1)
      call grab_result(code, result)
      end subroutine f2pywrap_gwswex_grab_result
      subroutine f2pywrap_gwswex_update_ini (auto_advance, gw_ini, sw_in&
     &i, f2py_gw_ini_d0, f2py_sw_ini_d0)
      use gwswex, only : update_ini
                use model, only: init_ts,solve_e
      logical(kind=1) auto_advance
      integer f2py_gw_ini_d0
      integer f2py_sw_ini_d0
      real(kind=8) gw_ini(f2py_gw_ini_d0)
      real(kind=8) sw_ini(f2py_sw_ini_d0)
      call update_ini(auto_advance, gw_ini, sw_ini)
      end subroutine f2pywrap_gwswex_update_ini
      subroutine f2pywrap_gwswex_resolve (gws_ext, sws_ext, f2py_gws_ext&
     &_d0, f2py_gws_ext_d1, f2py_sws_ext_d0, f2py_sws_ext_d1)
      use gwswex, only : resolve
                use model, only: resolve_l
      integer f2py_gws_ext_d0
      integer f2py_gws_ext_d1
      integer f2py_sws_ext_d0
      integer f2py_sws_ext_d1
      real(kind=8) gws_ext(f2py_gws_ext_d0,f2py_gws_ext_d1)
      real(kind=8) sws_ext(f2py_sws_ext_d0,f2py_sws_ext_d1)
      call resolve(gws_ext, sws_ext)
      end subroutine f2pywrap_gwswex_resolve
      subroutine f2pywrap_gwswex_pass_vars (gws, sws, sms, epv, f2py_gws&
     &_d0, f2py_gws_d1, f2py_sws_d0, f2py_sws_d1, f2py_sms_d0, f2py_sms_&
     &d1, f2py_epv_d0, f2py_epv_d1)
      use gwswex, only : pass_vars
                use model, only: gw,sw,uz
      integer f2py_gws_d0
      integer f2py_gws_d1
      integer f2py_sws_d0
      integer f2py_sws_d1
      integer f2py_sms_d0
      integer f2py_sms_d1
      integer f2py_epv_d0
      integer f2py_epv_d1
      real(kind=8) gws(f2py_gws_d0,f2py_gws_d1)
      real(kind=8) sws(f2py_sws_d0,f2py_sws_d1)
      real(kind=8) sms(f2py_sms_d0,f2py_sms_d1)
      real(kind=8) epv(f2py_epv_d0,f2py_epv_d1)
      call pass_vars(gws, sws, sms, epv)
      end subroutine f2pywrap_gwswex_pass_vars
      subroutine f2pywrap_gwswex_pass_vars_nlay (gws, sws, sms, epv, f2p&
     &y_gws_d0, f2py_gws_d1, f2py_sws_d0, f2py_sws_d1, f2py_sms_d0, f2py&
     &_sms_d1, f2py_sms_d2, f2py_epv_d0, f2py_epv_d1, f2py_epv_d2)
      use gwswex, only : pass_vars_nlay
                use model, only: gw,sw,uz,uz_,nelements
      integer f2py_gws_d0
      integer f2py_gws_d1
      integer f2py_sws_d0
      integer f2py_sws_d1
      integer f2py_sms_d0
      integer f2py_sms_d1
      integer f2py_sms_d2
      integer f2py_epv_d0
      integer f2py_epv_d1
      integer f2py_epv_d2
      real(kind=8) gws(f2py_gws_d0,f2py_gws_d1)
      real(kind=8) sws(f2py_sws_d0,f2py_sws_d1)
      real(kind=8) sms(f2py_sms_d0,f2py_sms_d1,f2py_sms_d2)
      real(kind=8) epv(f2py_epv_d0,f2py_epv_d1,f2py_epv_d2)
      call pass_vars_nlay(gws, sws, sms, epv)
      end subroutine f2pywrap_gwswex_pass_vars_nlay
      subroutine f2pywrap_gwswex_pass_dis (gw_dis, uz_dis, sw_dis, qdiff&
     &_l, f2py_gw_dis_d0, f2py_gw_dis_d1, f2py_uz_dis_d0, f2py_uz_dis_d1&
     &, f2py_sw_dis_d0, f2py_sw_dis_d1, f2py_qdiff_l_d0, f2py_qdiff_l_d1&
     &)
      use gwswex, only : pass_dis
                use model, only: gw,sw,uz,qdiff,qin,qout
      integer f2py_gw_dis_d0
      integer f2py_gw_dis_d1
      integer f2py_uz_dis_d0
      integer f2py_uz_dis_d1
      integer f2py_sw_dis_d0
      integer f2py_sw_dis_d1
      integer f2py_qdiff_l_d0
      integer f2py_qdiff_l_d1
      real(kind=8) gw_dis(f2py_gw_dis_d0,f2py_gw_dis_d1)
      real(kind=8) uz_dis(f2py_uz_dis_d0,f2py_uz_dis_d1)
      real(kind=8) sw_dis(f2py_sw_dis_d0,f2py_sw_dis_d1)
      real(kind=8) qdiff_l(f2py_qdiff_l_d0,f2py_qdiff_l_d1)
      call pass_dis(gw_dis, uz_dis, sw_dis, qdiff_l)
      end subroutine f2pywrap_gwswex_pass_dis
      
      subroutine f2pyinitgwswex(f2pysetupfunc)
      use gwswex, only : strlen
      use gwswex, only : update
      use gwswex, only : run
      use gwswex, only : finalize
      interface 
      subroutine f2pywrap_gwswex_init (config_path, gw_ini, sw_ini, f2py&
     &_gw_ini_d0, f2py_sw_ini_d0)
      integer f2py_gw_ini_d0
      integer f2py_sw_ini_d0
      character(len=*) config_path
      real(kind=8) gw_ini(f2py_gw_ini_d0)
      real(kind=8) sw_ini(f2py_sw_ini_d0)
      end subroutine f2pywrap_gwswex_init 
      subroutine f2pywrap_gwswex_get_lnts (get_lntsf2pywrap, get_lnts)
      integer get_lnts
      integer get_lntsf2pywrap
      end subroutine f2pywrap_gwswex_get_lnts 
      subroutine f2pywrap_gwswex_get_gts (get_gtsf2pywrap, get_gts)
      integer get_gts
      integer get_gtsf2pywrap
      end subroutine f2pywrap_gwswex_get_gts 
      subroutine f2pywrap_gwswex_get_curr_time_unix (get_curr_time_unixf&
     &2pywrap, get_curr_time_unix)
      integer get_curr_time_unix
      integer get_curr_time_unixf2pywrap
      end subroutine f2pywrap_gwswex_get_curr_time_unix 
      subroutine f2pywrap_gwswex_grab_result (code, result, f2py_result_&
     &d0, f2py_result_d1)
      integer f2py_result_d0
      integer f2py_result_d1
      character(len=*) code
      real(kind=8) result(f2py_result_d0,f2py_result_d1)
      end subroutine f2pywrap_gwswex_grab_result 
      subroutine f2pywrap_gwswex_update_ini (auto_advance, gw_ini, sw_in&
     &i, f2py_gw_ini_d0, f2py_sw_ini_d0)
      logical(kind=1) auto_advance
      integer f2py_gw_ini_d0
      integer f2py_sw_ini_d0
      real(kind=8) gw_ini(f2py_gw_ini_d0)
      real(kind=8) sw_ini(f2py_sw_ini_d0)
      end subroutine f2pywrap_gwswex_update_ini 
      subroutine f2pywrap_gwswex_resolve (gws_ext, sws_ext, f2py_gws_ext&
     &_d0, f2py_gws_ext_d1, f2py_sws_ext_d0, f2py_sws_ext_d1)
      integer f2py_gws_ext_d0
      integer f2py_gws_ext_d1
      integer f2py_sws_ext_d0
      integer f2py_sws_ext_d1
      real(kind=8) gws_ext(f2py_gws_ext_d0,f2py_gws_ext_d1)
      real(kind=8) sws_ext(f2py_sws_ext_d0,f2py_sws_ext_d1)
      end subroutine f2pywrap_gwswex_resolve 
      subroutine f2pywrap_gwswex_pass_vars (gws, sws, sms, epv, f2py_gws&
     &_d0, f2py_gws_d1, f2py_sws_d0, f2py_sws_d1, f2py_sms_d0, f2py_sms_&
     &d1, f2py_epv_d0, f2py_epv_d1)
      integer f2py_gws_d0
      integer f2py_gws_d1
      integer f2py_sws_d0
      integer f2py_sws_d1
      integer f2py_sms_d0
      integer f2py_sms_d1
      integer f2py_epv_d0
      integer f2py_epv_d1
      real(kind=8) gws(f2py_gws_d0,f2py_gws_d1)
      real(kind=8) sws(f2py_sws_d0,f2py_sws_d1)
      real(kind=8) sms(f2py_sms_d0,f2py_sms_d1)
      real(kind=8) epv(f2py_epv_d0,f2py_epv_d1)
      end subroutine f2pywrap_gwswex_pass_vars 
      subroutine f2pywrap_gwswex_pass_vars_nlay (gws, sws, sms, epv, f2p&
     &y_gws_d0, f2py_gws_d1, f2py_sws_d0, f2py_sws_d1, f2py_sms_d0, f2py&
     &_sms_d1, f2py_sms_d2, f2py_epv_d0, f2py_epv_d1, f2py_epv_d2)
      integer f2py_gws_d0
      integer f2py_gws_d1
      integer f2py_sws_d0
      integer f2py_sws_d1
      integer f2py_sms_d0
      integer f2py_sms_d1
      integer f2py_sms_d2
      integer f2py_epv_d0
      integer f2py_epv_d1
      integer f2py_epv_d2
      real(kind=8) gws(f2py_gws_d0,f2py_gws_d1)
      real(kind=8) sws(f2py_sws_d0,f2py_sws_d1)
      real(kind=8) sms(f2py_sms_d0,f2py_sms_d1,f2py_sms_d2)
      real(kind=8) epv(f2py_epv_d0,f2py_epv_d1,f2py_epv_d2)
      end subroutine f2pywrap_gwswex_pass_vars_nlay 
      subroutine f2pywrap_gwswex_pass_dis (gw_dis, uz_dis, sw_dis, qdiff&
     &_l, f2py_gw_dis_d0, f2py_gw_dis_d1, f2py_uz_dis_d0, f2py_uz_dis_d1&
     &, f2py_sw_dis_d0, f2py_sw_dis_d1, f2py_qdiff_l_d0, f2py_qdiff_l_d1&
     &)
      integer f2py_gw_dis_d0
      integer f2py_gw_dis_d1
      integer f2py_uz_dis_d0
      integer f2py_uz_dis_d1
      integer f2py_sw_dis_d0
      integer f2py_sw_dis_d1
      integer f2py_qdiff_l_d0
      integer f2py_qdiff_l_d1
      real(kind=8) gw_dis(f2py_gw_dis_d0,f2py_gw_dis_d1)
      real(kind=8) uz_dis(f2py_uz_dis_d0,f2py_uz_dis_d1)
      real(kind=8) sw_dis(f2py_sw_dis_d0,f2py_sw_dis_d1)
      real(kind=8) qdiff_l(f2py_qdiff_l_d0,f2py_qdiff_l_d1)
      end subroutine f2pywrap_gwswex_pass_dis
      end interface
      external f2pysetupfunc
      call f2pysetupfunc(strlen,f2pywrap_gwswex_init,f2pywrap_gwswex_get&
     &_lnts,f2pywrap_gwswex_get_gts,f2pywrap_gwswex_get_curr_time_unix,f&
     &2pywrap_gwswex_grab_result,update,f2pywrap_gwswex_update_ini,run,f&
     &2pywrap_gwswex_resolve,f2pywrap_gwswex_pass_vars,f2pywrap_gwswex_p&
     &ass_vars_nlay,f2pywrap_gwswex_pass_dis,finalize)
      end subroutine f2pyinitgwswex


